project:
  type: website
  render:
    - "*.qmd"
    - "!posts/2024-08-09-learning-Julia/index.qmd"

execute: 
  freeze: auto

website:
  title: "Kyle Belanger"
  navbar:
    right:
      - blog.qmd
      - text: "Resume"
        file: kyle_resume.pdf
      - icon: github
        href: https://github.com/mmmmtoasty19
format:
  html:
    theme: flatly
    css: styles.css



